### ISSUE TITLE
How to make my fonts looks like you?

### ISSUE THREAD

**Issue by soredake** [mfin/dotfiles#2]

**Comment by mfin** [comment]
My font configuration is pretty straightforward. I'm using Infinality bundle on Arch, urxvt is my terminal of choice and I'm using this beautiful new font called [Candy](https://bitbucket.org/sshdw/candy-font.git).

**Comment by soredake** [comment]
Can you please add your infinality and fontconfig configs to repo?

**Comment by mfin** [comment]
I've added my fontconfig. Infinality is at the default settings.
